const express = require('express');
const fs = require('fs');
const xlsx = require('node-xlsx');
const excel = require('excel-export');
const bodyParser = require('body-parser');
const multer = require('multer');
var open = require('child_process');
const data = [
    { "role": "consumer", "role_position": 1, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王雍岩", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13789828371_b9Fpa6TnBG@bgame.applysquare.net", "id": "bgame:b9Fpa6UT98", "site": "bgame", "tags": ["bgame:user"], "username": "13789828371b9Fpa6U7fCbgame" }, "user_id": "bgame:b9Fpa6UT98" },
    { "role": "supplier", "role_position": 1, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "田然", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13589144969_bA7ceRPKYT@bgame.applysquare.net", "id": "bgame:bA7ceRPzWK", "site": "bgame", "tags": ["bgame:user"], "username": "13589144969bA7ceRPf2Pbgame" }, "user_id": "bgame:bA7ceRPzWK" },
    { "role": "manufacturer", "role_position": 1, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "穆惟楚", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13176441490_bAG9gu4Qaj@bgame.applysquare.net", "id": "bgame:bAG9gu55Yb", "site": "bgame", "tags": ["bgame:user"], "username": "13176441490bAG9gu4k4fbgame" }, "user_id": "bgame:bAG9gu55Yb" },
    { "role": "dealer", "role_position": 1, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "吴志程", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13553164609_bAG7ndMamf@bgame.applysquare.net", "id": "bgame:bAG7ndNFjX", "site": "bgame", "tags": ["bgame:user"], "username": "13553164609bAG7ndMvFbbgame" }, "user_id": "bgame:bAG7ndNFjX" },
    { "role": "consumer", "role_position": 2, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "周宗艺", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "17860531635_bAQGNFhZEb@bgame.applysquare.net", "id": "bgame:bAQGNFiECT", "site": "bgame", "tags": ["bgame:user"], "username": "17860531635bAQGNFhtiXbgame" }, "user_id": "bgame:bAQGNFiECT" },
    { "role": "supplier", "role_position": 2, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘力铭", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15053960177_bBNNq5LdjT@bgame.applysquare.net", "id": "bgame:bBNNq5MJhK", "site": "bgame", "tags": ["bgame:user"], "username": "15053960177bBNNq5LyDPbgame" }, "user_id": "bgame:bBNNq5MJhK" },
    { "role": "manufacturer", "role_position": 2, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "张运征", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18254040758_bBNaYYMDTa@bgame.applysquare.net", "id": "bgame:bBNaYYMtRS", "site": "bgame", "tags": ["bgame:user"], "username": "18254040758bBNaYYMYwWbgame" }, "user_id": "bgame:bBNaYYMtRS" },
    { "role": "dealer", "role_position": 2, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "龚薪硕", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15069247869_bBNkJLVj2M@bgame.applysquare.net", "id": "bgame:bBNkJLWPzD", "site": "bgame", "tags": ["bgame:user"], "username": "15069247869bBNkJLW4WHbgame" }, "user_id": "bgame:bBNkJLWPzD" },
    { "role": "consumer", "role_position": 3, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王锐", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15865267258_bBRKXwr51E@bgame.applysquare.net", "id": "bgame:bBRKXwrjy6", "site": "bgame", "tags": ["bgame:user"], "username": "15865267258bBRKXwrQVAbgame" }, "user_id": "bgame:bBRKXwrjy6" },
    { "role": "supplier", "role_position": 3, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "陈俊逸", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15165053756_bBSfwCBVy7@bgame.applysquare.net", "id": "bgame:bBSfwCCAvy", "site": "bgame", "tags": ["bgame:user"], "username": "15165053756bBSfwCBqT3bgame" }, "user_id": "bgame:bBSfwCCAvy" },
    { "role": "manufacturer", "role_position": 3, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "孙凡珈", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18560013302_bBT4iKXaPN@bgame.applysquare.net", "id": "bgame:bBT4iKYFME", "site": "bgame", "tags": ["bgame:user"], "username": "18560013302bBT4iKXusJbgame" }, "user_id": "bgame:bBT4iKYFME" },
    { "role": "dealer", "role_position": 3, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李子涵", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13256719121_bBTKCSLXLy@bgame.applysquare.net", "id": "bgame:bBTKCSMCJq", "site": "bgame", "tags": ["bgame:user"], "username": "13256719121bBTKCSLrpubgame" }, "user_id": "bgame:bBTKCSMCJq" },
    { "role": "consumer", "role_position": 4, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "苏烁橦", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660811973_bBUJXqXL5a@bgame.applysquare.net", "id": "bgame:bBUJXqY13S", "site": "bgame", "tags": ["bgame:user"], "username": "18660811973bBUJXqXfZWbgame" }, "user_id": "bgame:bBUJXqY13S" },
    { "role": "supplier", "role_position": 4, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "高山佳月", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15106974671_bBVn8q6j6u@bgame.applysquare.net", "id": "bgame:bBVn8q7Q4m", "site": "bgame", "tags": ["bgame:user"], "username": "15106974671bBVn8q74aqbgame" }, "user_id": "bgame:bBVn8q7Q4m" },
    { "role": "manufacturer", "role_position": 4, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘文哲", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15554138662_bBVxNyNZx9@bgame.applysquare.net", "id": "bgame:bBVxNyPEv1", "site": "bgame", "tags": ["bgame:user"], "username": "15554138662bBVxNyNuS5bgame" }, "user_id": "bgame:bBVxNyPEv1" },
    { "role": "dealer", "role_position": 4, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "东野瑞欣", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15153114959_bBW3TvTgj7@bgame.applysquare.net", "id": "bgame:bBW3TvUMgy", "site": "bgame", "tags": ["bgame:user"], "username": "15153114959bBW3TvU2D3bgame" }, "user_id": "bgame:bBW3TvUMgy" },
    { "role": "consumer", "role_position": 5, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "段德望", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18678832598_bBXfpCd5Ge@bgame.applysquare.net", "id": "bgame:bBXfpCdkEW", "site": "bgame", "tags": ["bgame:user"], "username": "18678832598bBXfpCdQkabgame" }, "user_id": "bgame:bBXfpCdkEW" },
    { "role": "supplier", "role_position": 5, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "马瑞铭", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18560767388_bBY5MC1Var@bgame.applysquare.net", "id": "bgame:bBY5MC2AYi", "site": "bgame", "tags": ["bgame:user"], "username": "18560767388bBY5MC1q4nbgame" }, "user_id": "bgame:bBY5MC2AYi" },
    { "role": "manufacturer", "role_position": 5, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵陆博", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "17866600791_bBY5q6wyKQ@bgame.applysquare.net", "id": "bgame:bBY5q6xeHG", "site": "bgame", "tags": ["bgame:user"], "username": "17866600791bBY5q6xJoLbgame" }, "user_id": "bgame:bBY5q6xeHG" },
    { "role": "dealer", "role_position": 5, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘兆熙", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15005412856_bBY8VLdc2n@bgame.applysquare.net", "id": "bgame:bBY8VLeGze", "site": "bgame", "tags": ["bgame:user"], "username": "15005412856bBY8VLdwWibgame" }, "user_id": "bgame:bBY8VLeGze" },
    { "role": "consumer", "role_position": 6, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王嘉骏", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15966320183_bBYd3kXBiJ@bgame.applysquare.net", "id": "bgame:bBYd3kXrgA", "site": "bgame", "tags": ["bgame:user"], "username": "15966320183bBYd3kXXCEbgame" }, "user_id": "bgame:bBYd3kXrgA" },
    { "role": "supplier", "role_position": 6, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "冯佳琪", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18764141770_bBYe5vRhc6@bgame.applysquare.net", "id": "bgame:bBYe5vSNZx", "site": "bgame", "tags": ["bgame:user"], "username": "18764141770bBYe5vS362bgame" }, "user_id": "bgame:bBYe5vSNZx" },
    { "role": "manufacturer", "role_position": 6, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "闫玲玉", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15064053303_bBY5PYQMWa@bgame.applysquare.net", "id": "bgame:bBY5PYR2US", "site": "bgame", "tags": ["bgame:user"], "username": "15064053303bBY5PYQgzWbgame" }, "user_id": "bgame:bBY5PYR2US" },
    { "role": "dealer", "role_position": 6, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "韩东宏", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15106906197_bBZ12Qbgo4@bgame.applysquare.net", "id": "bgame:bBZ12QcMkv", "site": "bgame", "tags": ["bgame:user"], "username": "15106906197bBZ12Qc2Gzbgame" }, "user_id": "bgame:bBZ12QcMkv" },
    { "role": "consumer", "role_position": 7, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵明", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15806663150_bBZ4PPTERQ@bgame.applysquare.net", "id": "bgame:bBZ4PPTuPG", "site": "bgame", "tags": ["bgame:user"], "username": "15806663150bBZ4PPTZuLbgame" }, "user_id": "bgame:bBZ4PPTuPG" },
    { "role": "supplier", "role_position": 7, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "骆安琪", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13256111117_bBZDPxbm1t@bgame.applysquare.net", "id": "bgame:bBZDPxcRyk", "site": "bgame", "tags": ["bgame:user"], "username": "13256111117bBZDPxc6Vpbgame" }, "user_id": "bgame:bBZDPxcRyk" },
    { "role": "manufacturer", "role_position": 7, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘馨璐", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15269131060_bBa8QaYdte@bgame.applysquare.net", "id": "bgame:bBa8QaZJrW", "site": "bgame", "tags": ["bgame:user"], "username": "15269131060bBa8QaYyNabgame" }, "user_id": "bgame:bBa8QaZJrW" },
    { "role": "dealer", "role_position": 7, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "杨可意", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15054199167_bBaCQNG1qc@bgame.applysquare.net", "id": "bgame:bBaCQNGgoU", "site": "bgame", "tags": ["bgame:user"], "username": "15054199167bBaCQNGMKYbgame" }, "user_id": "bgame:bBaCQNGgoU" },
    { "role": "consumer", "role_position": 8, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "薛功泰", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15166413256_bBaAwm3LYA@bgame.applysquare.net", "id": "bgame:bBaAwm41W2", "site": "bgame", "tags": ["bgame:user"], "username": "15166413256bBaAwm3g26bgame" }, "user_id": "bgame:bBaAwm41W2" },
    { "role": "supplier", "role_position": 8, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "郭晓玉", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15169123592_bBaP45SnoU@bgame.applysquare.net", "id": "bgame:bBaP45TTmL", "site": "bgame", "tags": ["bgame:user"], "username": "15169123592bBaP45T8HQbgame" }, "user_id": "bgame:bBaP45TTmL" },
    { "role": "manufacturer", "role_position": 8, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘泽乔泰", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13625413566_bBaePMBzt2@bgame.applysquare.net", "id": "bgame:bBaePMCfqt", "site": "bgame", "tags": ["bgame:user"], "username": "13625413566bBaePMCLMxbgame" }, "user_id": "bgame:bBaePMCfqt" },
    { "role": "dealer", "role_position": 8, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "狄泽群", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15605411128_bBakijpgTL@bgame.applysquare.net", "id": "bgame:bBakijqMRC", "site": "bgame", "tags": ["bgame:user"], "username": "15605411128bBakijq1wGbgame" }, "user_id": "bgame:bBakijqMRC" },
    { "role": "consumer", "role_position": 9, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "卢林", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15966696552_bBaGeuRFqL@bgame.applysquare.net", "id": "bgame:bBaGeuRvoC", "site": "bgame", "tags": ["bgame:user"], "username": "15966696552bBaGeuRbKGbgame" }, "user_id": "bgame:bBaGeuRvoC" },
    { "role": "supplier", "role_position": 9, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘雅宁", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15910085863_bBUgC4hNYV@bgame.applysquare.net", "id": "bgame:bBUgC4i3WM", "site": "bgame", "tags": ["bgame:user"], "username": "15910085863bBUgC4hi2Rbgame" }, "user_id": "bgame:bBUgC4i3WM" },
    { "role": "manufacturer", "role_position": 9, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "崔明月", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13256186912_bBb6R7ic2W@bgame.applysquare.net", "id": "bgame:bBb6R7jGzN", "site": "bgame", "tags": ["bgame:user"], "username": "13256186912bBb6R7iwWSbgame" }, "user_id": "bgame:bBb6R7jGzN" },
    { "role": "dealer", "role_position": 9, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王辰昊", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15550475019_bBb3rWDHNJ@bgame.applysquare.net", "id": "bgame:bBb3rWDxLA", "site": "bgame", "tags": ["bgame:user"], "username": "15550475019bBb3rWDcrEbgame" }, "user_id": "bgame:bBb3rWDxLA" },
    { "role": "consumer", "role_position": 10, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘海冰", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660190720_bBbaM6yqwQ@bgame.applysquare.net", "id": "bgame:bBbaM6zWuG", "site": "bgame", "tags": ["bgame:user"], "username": "18660190720bBbaM6zBRLbgame" }, "user_id": "bgame:bBbaM6zWuG" },
    { "role": "supplier", "role_position": 10, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "侯玙萱", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15194128425_bBcFuRGjtN@bgame.applysquare.net", "id": "bgame:bBcFuRHQrE", "site": "bgame", "tags": ["bgame:user"], "username": "15194128425bBcFuRH5NJbgame" }, "user_id": "bgame:bBcFuRHQrE" },
    { "role": "manufacturer", "role_position": 10, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "姜云霄", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13370512860_bBcFozy2fL@bgame.applysquare.net", "id": "bgame:bBcFozyhdC", "site": "bgame", "tags": ["bgame:user"], "username": "13370512860bBcFozyN9Gbgame" }, "user_id": "bgame:bBcFozyhdC" },
    { "role": "dealer", "role_position": 10, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "张梦君", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15665751631_bBcfFU8o4v@bgame.applysquare.net", "id": "bgame:bBcfFU9U2n", "site": "bgame", "tags": ["bgame:user"], "username": "15665751631bBcfFU98Yrbgame" }, "user_id": "bgame:bBcfFU9U2n" },
    { "role": "consumer", "role_position": 11, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘宏凯", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13964191561_bBcuVW4JUS@bgame.applysquare.net", "id": "bgame:bBcuVW4ySJ", "site": "bgame", "tags": ["bgame:user"], "username": "13964191561bBcuVW4dxNbgame" }, "user_id": "bgame:bBcuVW4ySJ" },
    { "role": "supplier", "role_position": 11, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王宸", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13335193165_bBdHQJH1V4@bgame.applysquare.net", "id": "bgame:bBdHQJHgSv", "site": "bgame", "tags": ["bgame:user"], "username": "13335193165bBdHQJHLxzbgame" }, "user_id": "bgame:bBdHQJHgSv" },
    { "role": "manufacturer", "role_position": 11, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵家梁", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660188736_bBdLZ5xUVg@bgame.applysquare.net", "id": "bgame:bBdLZ5y9TY", "site": "bgame", "tags": ["bgame:user"], "username": "18660188736bBdLZ5xoycbgame" }, "user_id": "bgame:bBdLZ5y9TY" },
    { "role": "dealer", "role_position": 11, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王若娴", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18853139610_bBdQp7GUQA@bgame.applysquare.net", "id": "bgame:bBdQp7H9N2", "site": "bgame", "tags": ["bgame:user"], "username": "18853139610bBdQp7Got6bgame" }, "user_id": "bgame:bBdQp7H9N2" },
    { "role": "consumer", "role_position": 12, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "朱连超", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13655313319_bBes6HnU2W@bgame.applysquare.net", "id": "bgame:bBes6Ho8zN", "site": "bgame", "tags": ["bgame:user"], "username": "13655313319bBes6HnoWSbgame" }, "user_id": "bgame:bBes6Ho8zN" },
    { "role": "supplier", "role_position": 12, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "商亚轩", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15165159960_bBfR9CPxBk@bgame.applysquare.net", "id": "bgame:bBfR9CQd9c", "site": "bgame", "tags": ["bgame:user"], "username": "15165159960bBfR9CQHfgbgame" }, "user_id": "bgame:bBfR9CQd9c" },
    { "role": "manufacturer", "role_position": 12, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘佚", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15725158786_bBfRrqTo4E@bgame.applysquare.net", "id": "bgame:bBfRrqUU26", "site": "bgame", "tags": ["bgame:user"], "username": "15725158786bBfRrqU8YAbgame" }, "user_id": "bgame:bBfRrqUU26" },
    { "role": "dealer", "role_position": 12, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "张雅雯", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18363067299_bBg2JHUpmY@bgame.applysquare.net", "id": "bgame:bBg2JHVVjQ", "site": "bgame", "tags": ["bgame:user"], "username": "18363067299bBg2JHVAFUbgame" }, "user_id": "bgame:bBg2JHVVjQ" },
    { "role": "consumer", "role_position": 13, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "张雨萌", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18396847958_bBg6XSZQRg@bgame.applysquare.net", "id": "bgame:bBg6XSa5PY", "site": "bgame", "tags": ["bgame:user"], "username": "18396847958bBg6XSZjucbgame" }, "user_id": "bgame:bBg6XSa5PY" },
    { "role": "supplier", "role_position": 13, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "胡渊博", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13188935723_bBhXtUs9B8@bgame.applysquare.net", "id": "bgame:bBhXtUsp8z", "site": "bgame", "tags": ["bgame:user"], "username": "13188935723bBhXtUsUf4bgame" }, "user_id": "bgame:bBhXtUsp8z" },
    { "role": "manufacturer", "role_position": 13, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "沙玉琪", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15726109088_bBhD42NNpJ@bgame.applysquare.net", "id": "bgame:bBhD42P3nA", "site": "bgame", "tags": ["bgame:user"], "username": "15726109088bBhD42NiJEbgame" }, "user_id": "bgame:bBhD42P3nA" },
    { "role": "dealer", "role_position": 13, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "金顺", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18954103582_bBhiCnoyQN@bgame.applysquare.net", "id": "bgame:bBhiCnpeNE", "site": "bgame", "tags": ["bgame:user"], "username": "18954103582bBhiCnpJtJbgame" }, "user_id": "bgame:bBhiCnpeNE" },
    { "role": "consumer", "role_position": 14, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王冉", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18678836015_bBi13Xp9fp@bgame.applysquare.net", "id": "bgame:bBi13Xppdg", "site": "bgame", "tags": ["bgame:user"], "username": "18678836015bBi13XpV9kbgame" }, "user_id": "bgame:bBi13Xppdg" },
    { "role": "supplier", "role_position": 14, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王子晗", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13370518467_bC7rP1STMt@bgame.applysquare.net", "id": "bgame:bC7rP1T8Kk", "site": "bgame", "tags": ["bgame:user"], "username": "13370518467bC7rP1Snqpbgame" }, "user_id": "bgame:bC7rP1T8Kk" },
    { "role": "manufacturer", "role_position": 14, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "孙鑫鑫", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15614684786_bC7JVZNixA@bgame.applysquare.net", "id": "bgame:bC7JVZPPv2", "site": "bgame", "tags": ["bgame:user"], "username": "15614684786bC7JVZP4S6bgame" }, "user_id": "bgame:bC7JVZPPv2" },
    { "role": "dealer", "role_position": 14, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李智", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15854153915_bC8UMPE6cS@bgame.applysquare.net", "id": "bgame:bC8UMPEmaJ", "site": "bgame", "tags": ["bgame:user"], "username": "15854153915bC8UMPES6Nbgame" }, "user_id": "bgame:bC8UMPEmaJ" },
    { "role": "consumer", "role_position": 15, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "谈若瑶", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15764151525_bC8tecu5jY@bgame.applysquare.net", "id": "bgame:bC8tecukhQ", "site": "bgame", "tags": ["bgame:user"], "username": "15764151525bC8tecuRDUbgame" }, "user_id": "bgame:bC8tecukhQ" },
    { "role": "supplier", "role_position": 15, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王瑞", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13165134839_bCCzWKG17p@bgame.applysquare.net", "id": "bgame:bCCzWKGg5g", "site": "bgame", "tags": ["bgame:user"], "username": "13165134839bCCzWKGLbkbgame" }, "user_id": "bgame:bCCzWKGg5g" },
    { "role": "manufacturer", "role_position": 15, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王晓越", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15069182086_bCFWMpYHK8@bgame.applysquare.net", "id": "bgame:bCFWMpYxGz", "site": "bgame", "tags": ["bgame:user"], "username": "15069182086bCFWMpYco4bgame" }, "user_id": "bgame:bCFWMpYxGz" },
    { "role": "dealer", "role_position": 15, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "夏浩鑫", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13685317758_bCFPNxW4Ui@bgame.applysquare.net", "id": "bgame:bCFPNxWjSa", "site": "bgame", "tags": ["bgame:user"], "username": "13685317758bCFPNxWPxebgame" }, "user_id": "bgame:bCFPNxWjSa" },
    { "role": "consumer", "role_position": 16, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "霍玉豪", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13969090302_bCGcrnx2x2@bgame.applysquare.net", "id": "bgame:bCGcrnxhut", "site": "bgame", "tags": ["bgame:user"], "username": "13969090302bCGcrnxNRxbgame" }, "user_id": "bgame:bCGcrnxhut" },
    { "role": "supplier", "role_position": 16, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "陆佳乐", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15269106929_bCHQyL641g@bgame.applysquare.net", "id": "bgame:bCHQyL6iyY", "site": "bgame", "tags": ["bgame:user"], "username": "15269106929bCHQyL6PVcbgame" }, "user_id": "bgame:bCHQyL6iyY" },
    { "role": "manufacturer", "role_position": 16, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "乔昕雨", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15254152107_bCLKTaSQo4@bgame.applysquare.net", "id": "bgame:bCLKTaT5kv", "site": "bgame", "tags": ["bgame:user"], "username": "15254152107bCLKTaSkGzbgame" }, "user_id": "bgame:bCLKTaT5kv" },
    { "role": "dealer", "role_position": 16, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "侯爽", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15098712168_bCPE6sbgm8@bgame.applysquare.net", "id": "bgame:bCPE6scMiz", "site": "bgame", "tags": ["bgame:user"], "username": "15098712168bCPE6sc2F4bgame" }, "user_id": "bgame:bCPE6scMiz" },
    { "role": "consumer", "role_position": 17, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵文灏", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13335297527_bCPF2hqwjG@bgame.applysquare.net", "id": "bgame:bCPF2hrch8", "site": "bgame", "tags": ["bgame:user"], "username": "13335297527bCPF2hrHDCbgame" }, "user_id": "bgame:bCPF2hrch8" },
    { "role": "supplier", "role_position": 17, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李雨潼", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15656195789_bCP8QhZeTk@bgame.applysquare.net", "id": "bgame:bCP8QhaKRc", "site": "bgame", "tags": ["bgame:user"], "username": "15656195789bCP8QhZywgbgame" }, "user_id": "bgame:bCP8QhaKRc" },
    { "role": "manufacturer", "role_position": 17, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "蔡家驹", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18560027695_bCPTZL9czW@bgame.applysquare.net", "id": "bgame:bCPTZLAHxN", "site": "bgame", "tags": ["bgame:user"], "username": "18560027695bCPTZL9xUSbgame" }, "user_id": "bgame:bCPTZLAHxN" },
    { "role": "dealer", "role_position": 17, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "翟芷菁", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13065065016_bBe1SRMuQ6@bgame.applysquare.net", "id": "bgame:bBe1SRNaMx", "site": "bgame", "tags": ["bgame:user"], "username": "13065065016bBe1SRNEt2bgame" }, "user_id": "bgame:bBe1SRNaMx" },
    { "role": "consumer", "role_position": 18, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王新雅", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13082755936_bCPtvopnoC@bgame.applysquare.net", "id": "bgame:bCPtvoqTm4", "site": "bgame", "tags": ["bgame:user"], "username": "13082755936bCPtvoq8H8bgame" }, "user_id": "bgame:bCPtvoqTm4" },
    { "role": "supplier", "role_position": 18, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘淇", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13864163626_bCRhz1yN9g@bgame.applysquare.net", "id": "bgame:bCRhz1z37Y", "site": "bgame", "tags": ["bgame:user"], "username": "13864163626bCRhz1yhdcbgame" }, "user_id": "bgame:bCRhz1z37Y" },
    { "role": "manufacturer", "role_position": 18, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李泽洋", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15069137502_bCSsou9Lup@bgame.applysquare.net", "id": "bgame:bCSsouA1sg", "site": "bgame", "tags": ["bgame:user"], "username": "15069137502bCSsou9gPkbgame" }, "user_id": "bgame:bCSsouA1sg" },
    { "role": "dealer", "role_position": 18, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李新玥", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13864134573_bCU25J7Twg@bgame.applysquare.net", "id": "bgame:bCU25J88uY", "site": "bgame", "tags": ["bgame:user"], "username": "13864134573bCU25J7oRcbgame" }, "user_id": "bgame:bCU25J88uY" },
    { "role": "consumer", "role_position": 19, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "孙晋楷", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18863261238_bCVEgX7xSE@bgame.applysquare.net", "id": "bgame:bCVEgX8dQ6", "site": "bgame", "tags": ["bgame:user"], "username": "18863261238bCVEgX8HvAbgame" }, "user_id": "bgame:bCVEgX8dQ6" },
    { "role": "supplier", "role_position": 19, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "万旭", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13065014199_bCWZyQQHiz@bgame.applysquare.net", "id": "bgame:bCWZyQQxgr", "site": "bgame", "tags": ["bgame:user"], "username": "13065014199bCWZyQQdCvbgame" }, "user_id": "bgame:bCWZyQQxgr" },
    { "role": "manufacturer", "role_position": 19, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "胡修华", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13012992922_bCX6fv3R6i@bgame.applysquare.net", "id": "bgame:bCX6fv464a", "site": "bgame", "tags": ["bgame:user"], "username": "13012992922bCX6fv3kaebgame" }, "user_id": "bgame:bCX6fv464a" },
    { "role": "dealer", "role_position": 19, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王扬", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15853110261_bCXRL55CW6@bgame.applysquare.net", "id": "bgame:bCXRL55sTx", "site": "bgame", "tags": ["bgame:user"], "username": "15853110261bCXRL55Xz2bgame" }, "user_id": "bgame:bCXRL55sTx" },
    { "role": "consumer", "role_position": 20, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "黄欣", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15005412933_bBRtSvmtz1@bgame.applysquare.net", "id": "bgame:bBRtSvnZws", "site": "bgame", "tags": ["bgame:user"], "username": "15005412933bBRtSvnETwbgame" }, "user_id": "bgame:bBRtSvnZws" },
    { "role": "supplier", "role_position": 20, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "宋宇轩", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660436552_bCXkebQNHY@bgame.applysquare.net", "id": "bgame:bCXkebR3FQ", "site": "bgame", "tags": ["bgame:user"], "username": "18660436552bCXkebQhmUbgame" }, "user_id": "bgame:bCXkebR3FQ" },
    { "role": "manufacturer", "role_position": 20, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "任悦悦", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15166413720_bCXN53ekjL@bgame.applysquare.net", "id": "bgame:bCXN53fRhC", "site": "bgame", "tags": ["bgame:user"], "username": "15166413720bCXN53f6DGbgame" }, "user_id": "bgame:bCXN53fRhC" },
    { "role": "dealer", "role_position": 20, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "丁宜章", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660115732_bCYQJWaQdG@bgame.applysquare.net", "id": "bgame:bCYQJWb5b8", "site": "bgame", "tags": ["bgame:user"], "username": "18660115732bCYQJWak7Cbgame" }, "user_id": "bgame:bCYQJWb5b8" },
    { "role": "consumer", "role_position": 21, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "张宇凡", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18605471535_bCYejqnnst@bgame.applysquare.net", "id": "bgame:bCYejqoTqk", "site": "bgame", "tags": ["bgame:user"], "username": "18605471535bCYejqo8Mpbgame" }, "user_id": "bgame:bCYejqoTqk" },
    { "role": "supplier", "role_position": 21, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "宋俊睿", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13156190157_bCZTg5N3Gv@bgame.applysquare.net", "id": "bgame:bCZTg5NiEn", "site": "bgame", "tags": ["bgame:user"], "username": "13156190157bCZTg5NNkrbgame" }, "user_id": "bgame:bCZTg5NiEn" },
    { "role": "manufacturer", "role_position": 21, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "马名州", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13325103353_bCZzqCLdJJ@bgame.applysquare.net", "id": "bgame:bCZzqCMJGA", "site": "bgame", "tags": ["bgame:user"], "username": "13325103353bCZzqCLxnEbgame" }, "user_id": "bgame:bCZzqCMJGA" },
    { "role": "dealer", "role_position": 21, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "杨子豪", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13256113775_bCZnM3qRhL@bgame.applysquare.net", "id": "bgame:bCZnM3r6fC", "site": "bgame", "tags": ["bgame:user"], "username": "13256113775bCZnM3qmBGbgame" }, "user_id": "bgame:bCZnM3r6fC" },
    { "role": "consumer", "role_position": 22, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李焕涛", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18963063673_bCaULpje34@bgame.applysquare.net", "id": "bgame:bCaULpkJzv", "site": "bgame", "tags": ["bgame:user"], "username": "18963063673bCaULpjyWzbgame" }, "user_id": "bgame:bCaULpkJzv" },
    { "role": "supplier", "role_position": 22, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李向雨", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18660797918_bCasUwFVRL@bgame.applysquare.net", "id": "bgame:bCasUwGAPC", "site": "bgame", "tags": ["bgame:user"], "username": "18660797918bCasUwFpuGbgame" }, "user_id": "bgame:bCasUwGAPC" },
    { "role": "manufacturer", "role_position": 22, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "逯一诺", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18663794679_bCbJhLd4Bc@bgame.applysquare.net", "id": "bgame:bCbJhLdj9U", "site": "bgame", "tags": ["bgame:user"], "username": "18663794679bCbJhLdPfYbgame" }, "user_id": "bgame:bCbJhLdj9U" },
    { "role": "dealer", "role_position": 22, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘淑贤", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13127150587_bCbS9Nc5y4@bgame.applysquare.net", "id": "bgame:bCbS9Nckvv", "site": "bgame", "tags": ["bgame:user"], "username": "13127150587bCbS9NcRSzbgame" }, "user_id": "bgame:bCbS9Nckvv" },
    { "role": "consumer", "role_position": 23, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵延晟", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15063338672_bCc6wspYNv@bgame.applysquare.net", "id": "bgame:bCc6wsqDLn", "site": "bgame", "tags": ["bgame:user"], "username": "15063338672bCc6wspsrrbgame" }, "user_id": "bgame:bCc6wsqDLn" },
    { "role": "supplier", "role_position": 23, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "杨浩然", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15820099762_bCcSkG7EVx@bgame.applysquare.net", "id": "bgame:bCcSkG7uTp", "site": "bgame", "tags": ["bgame:user"], "username": "15820099762bCcSkG7Zytbgame" }, "user_id": "bgame:bCcSkG7uTp" },
    { "role": "manufacturer", "role_position": 23, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "焦体升", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15098828185_bCci28g5Ht@bgame.applysquare.net", "id": "bgame:bCci28gkFk", "site": "bgame", "tags": ["bgame:user"], "username": "15098828185bCci28gQmpbgame" }, "user_id": "bgame:bCci28gkFk" },
    { "role": "dealer", "role_position": 23, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李钊", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13864178890_bCcy583Arn@bgame.applysquare.net", "id": "bgame:bCcy583qpe", "site": "bgame", "tags": ["bgame:user"], "username": "13864178890bCcy583WLibgame" }, "user_id": "bgame:bCcy583qpe" },
    { "role": "consumer", "role_position": 24, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "尹嘉扬", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15969715107_bCdb4a6dRk@bgame.applysquare.net", "id": "bgame:bCdb4a7JPc", "site": "bgame", "tags": ["bgame:user"], "username": "15969715107bCdb4a6xugbgame" }, "user_id": "bgame:bCdb4a7JPc" },
    { "role": "supplier", "role_position": 24, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "韩昊", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13793177197_bCeooPQRNA@bgame.applysquare.net", "id": "bgame:bCeooPR6L2", "site": "bgame", "tags": ["bgame:user"], "username": "13793177197bCeooPQkr6bgame" }, "user_id": "bgame:bCeooPR6L2" },
    { "role": "manufacturer", "role_position": 24, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "薄阳侯", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15264111038_bCfFDPrMGE@bgame.applysquare.net", "id": "bgame:bCfFDPs2E6", "site": "bgame", "tags": ["bgame:user"], "username": "15264111038bCfFDPrgkAbgame" }, "user_id": "bgame:bCfFDPs2E6" },
    { "role": "dealer", "role_position": 24, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘方齐", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "17753160957_bCZwCoWtDx@bgame.applysquare.net", "id": "bgame:bCZwCoXZBp", "site": "bgame", "tags": ["bgame:user"], "username": "17753160957bCZwCoXDhtbgame" }, "user_id": "bgame:bCZwCoXZBp" },
    { "role": "consumer", "role_position": 25, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵伊梦", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15169185897_bCfs1DLmeS@bgame.applysquare.net", "id": "bgame:bCfs1DMScJ", "site": "bgame", "tags": ["bgame:user"], "username": "15169185897bCfs1DM78Nbgame" }, "user_id": "bgame:bCfs1DMScJ" },
    { "role": "supplier", "role_position": 25, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "毕明钰", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18353159059_bBfdsqW9Nz@bgame.applysquare.net", "id": "bgame:bBfdsqWpLr", "site": "bgame", "tags": ["bgame:user"], "username": "18353159059bBfdsqWUrvbgame" }, "user_id": "bgame:bBfdsqWpLr" },
    { "role": "manufacturer", "role_position": 25, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "高嘉恒", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13853117903_bChmJn9aoc@bgame.applysquare.net", "id": "bgame:bChmJnAFmU", "site": "bgame", "tags": ["bgame:user"], "username": "13853117903bChmJn9vHYbgame" }, "user_id": "bgame:bChmJnAFmU" },
    { "role": "dealer", "role_position": 25, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "燕春恒", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13081975813_bBceyYWADQ@bgame.applysquare.net", "id": "bgame:bBceyYWqBG", "site": "bgame", "tags": ["bgame:user"], "username": "13081975813bBceyYWVhLbgame" }, "user_id": "bgame:bBceyYWqBG" },
    { "role": "consumer", "role_position": 26, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "孙梦琳", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13064012083_bCiVuYSenE@bgame.applysquare.net", "id": "bgame:bCiVuYTKk6", "site": "bgame", "tags": ["bgame:user"], "username": "13064012083bCiVuYSzGAbgame" }, "user_id": "bgame:bCiVuYTKk6" },
    { "role": "supplier", "role_position": 26, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "李京军", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15305315959_bCnsGQHzJW@bgame.applysquare.net", "id": "bgame:bCnsGQJfGN", "site": "bgame", "tags": ["bgame:user"], "username": "15305315959bCnsGQJKnSbgame" }, "user_id": "bgame:bCnsGQJfGN" },
    { "role": "manufacturer", "role_position": 26, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "赵成硕", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "17615815223_bCpygcnR4e@bgame.applysquare.net", "id": "bgame:bCpygco62W", "site": "bgame", "tags": ["bgame:user"], "username": "17615815223bCpygcnkYabgame" }, "user_id": "bgame:bCpygco62W" },
    { "role": "dealer", "role_position": 26, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "辛怡萱", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "13011726706_bDDryMjqBx@bgame.applysquare.net", "id": "bgame:bDDryMkW9p", "site": "bgame", "tags": ["bgame:user"], "username": "13011726706bDDryMkAftbgame" }, "user_id": "bgame:bDDryMkW9p" },
    { "role": "consumer", "role_position": 27, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "王一鸣", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "15662742526_bDTMwXiiGS@bgame.applysquare.net", "id": "bgame:bDTMwXjPEJ", "site": "bgame", "tags": ["bgame:user"], "username": "15662742526bDTMwXj3kNbgame" }, "user_id": "bgame:bDTMwXjPEJ" },
    { "role": "supplier", "role_position": 27, "user": { "can_delete": false, "data": { "already_used": false, "bgame_token": null, "class": null, "college": null, "company": null, "division": null, "entryyear": null, "gender": null, "grade": null, "grade_name": null, "institute_slug": null, "interested_fos_keys": [], "job_title": null, "lang": null, "name": "刘士尊", "phone": null, "position": null, "positional_titles": null, "province": null, "school": null, "selected_elective_names": [], "stu_id": null, "subject": null }, "email": "18766404346_bDTo2d5Vkv@bgame.applysquare.net", "id": "bgame:bDTo2d6Ain", "site": "bgame", "tags": ["bgame:user"], "username": "18766404346bDTo2d5qErbgame" }, "user_id": "bgame:bDTo2d6Ain" }
];

const app = express();
app.use('/', express.static('./file'));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(multer({ dest: '/tmp/zsp' }).array('image'));
console.log(data)
app.get('/', function (req, res) {
    res.send(`<html>
    <head>
    <title>文件上传表单</title>
    </head>
    <body>
    <h3>文件上传：</h3>
    选择一个文件上传: <br />
    <form action="/file_upload" method="post" enctype="multipart/form-data">
    <input type="file" name="image" size="50" />
    <br />
    <input type="submit" value="上传文件" />
    </form>
    </body>
    </html>`);
})

// app.post('/file_upload', (req, res) => {
//     const sheet = xlsx.parse(req.files[0].path);
//     let cn = '';
//     let en = '';
let obj = {};
let rows = [];
let cols = [
    { caption: '姓名', type: 'string', width: 30 },
    { caption: 'ID', type: 'string', width: 30 },
    { caption: 'id', type: 'string', width: 30 },
]
// sheet.forEach(item => {
//     if (item.data.length > 0) {
//         item.data.forEach((list, index) => {
//             rows[index] = [

//             ]
//         })
//     }
// })
for (var i = 0; i < data.length; i++) {
    console.log(i, data[i])
    //依次写入
    rows[i] = [
        data[i]['user']['data']['name'],
        data[i]['user_id'],
        data[i]['user_id'],
    ];
}
obj.name = "mysheet";
obj.rows = rows;
obj.cols = cols;
let result = excel.execute([obj, obj, obj]);
fs.writeFileSync('./users.xlsx', result, 'binary')
// res.end();
// fs.writeFileSync('./file/cn.json', `{${cn}\r}`)
// fs.writeFileSync('./file/en.json', `{${en}\r}`)
// res.write(`<a href="en.json" download="en">en.json</a><br/>
// <a href="cn.json" download="cn">cn.json</a>`)
// res.end();
// })
// app.listen(8888);
// open.exec('open http://localhost:8888');